version: '3.5'

services:
  postgres:
    container_name: post-hacka-boiler
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: db
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  

networks:
  postgres:
    driver: bridge

volumes:
    postgres:

    
